# Generated by Django 5.1.2 on 2024-10-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_films_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='type',
            field=models.CharField(choices=[('FILM', 'Фильмы'), ('TV_SERIES', 'Сериалы')], max_length=255, verbose_name='Тип фильма'),
        ),
    ]
