# Generated by Django 5.1.2 on 2024-11-09 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('9503c4c4-acb8-4109-86a2-614d7169650e'), unique=True),
        ),
    ]
