# Generated by Django 5.1.2 on 2024-11-09 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('74adbb3a-7543-4237-9e7b-b3170d568136'), unique=True),
        ),
    ]
