# Generated by Django 5.1.2 on 2024-10-15 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_emailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('cf54db3a-99ae-4f60-943d-bad16d48dc8c'), unique=True),
        ),
    ]
