# Generated by Django 5.1.2 on 2024-10-24 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('daab8f39-18d1-4395-8553-74fb14f6dddc'), unique=True),
        ),
    ]
