# Generated by Django 5.1.2 on 2024-11-13 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c911cc67-5864-4704-a5cc-c24530cf3d18'), unique=True),
        ),
    ]
