# Generated by Django 5.1.2 on 2024-12-06 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('dafc916b-1739-4999-9fe6-ac6254485c35'), unique=True),
        ),
    ]
