# Generated by Django 5.1.2 on 2024-10-27 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d7754653-dd06-4511-9a5a-c78fc06c94eb'), unique=True),
        ),
    ]
