# Generated by Django 5.1.2 on 2024-10-27 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c5bdbbc7-6fd8-4ffd-8f83-26103d753d01'), unique=True),
        ),
    ]
