# Generated by Django 5.1.2 on 2024-11-02 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('22be66f7-a6db-40ce-b252-8b0065dc10f2'), unique=True),
        ),
    ]
