# Generated by Django 5.1.2 on 2024-11-02 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('59ffb34a-b89a-4f8b-b3bf-f261a6c6ecc6'), unique=True),
        ),
    ]
