# Generated by Django 5.1.2 on 2024-11-03 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_users_profile_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('311e7970-ade8-42fb-85c2-d7d8e57176a8'), unique=True),
        ),
    ]
