# Generated by Django 5.1.2 on 2024-11-03 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('97c684a9-d8ed-4c26-954e-6c96da20694c'), unique=True),
        ),
    ]
