# Generated by Django 5.1.2 on 2024-11-03 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('27ffd042-45b9-48a2-afd6-2de395744f9a'), unique=True),
        ),
    ]
