# Generated by Django 5.1.2 on 2024-11-03 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('65ea0141-3c92-40c7-bb6e-59acd4ab410e'), unique=True),
        ),
    ]
