# Generated by Django 5.1.2 on 2024-11-06 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('8d5bd286-c5ef-45f9-a120-b04579b2c508'), unique=True),
        ),
    ]
