# Generated by Django 5.1.2 on 2024-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Продолжительность фильма'),
        ),
    ]
