# Generated by Django 5.1.2 on 2024-11-06 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_films_options_alter_watch_later_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, max_length=5, verbose_name='Оценка фильма'),
        ),
        migrations.RemoveField(
            model_name='watch_later',
            name='film',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('grade', models.PositiveIntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.films')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='watch_later',
            name='film',
            field=models.ManyToManyField(to='core.films'),
        ),
    ]
